### ISSUE TITLE
Error in Annotation Worker

### ISSUE THREAD

**Issue by desaiuditd** [pandastrike/bayzee#2]
I'm getting following error log when I run the annotation worker. I successfully ran the annotation dispatcher.

```
Traceback (most recent call last):
  File "bin/worker", line 16, in <module>
    bayzee.annotate(configFilePath)
  File "/Users/udit/work/workspace/bayzee/__init__.py", line 82, in annotate
    ann.annotate()
  File "/Users/udit/work/workspace/bayzee/src/annotation_worker.py", line 74, in annotate
    processorInstance.annotate(self.config, documentId)
  File "/Users/udit/work/workspace/bayzee/lib/pos-processor.py", line 75, in annotate
    posTags = nltk.pos_tag(sentenceWords)
  File "/Library/Python/2.7/site-packages/nltk/tag/__init__.py", line 111, in pos_tag
    return _pos_tag(tokens, tagset, tagger)    
  File "/Library/Python/2.7/site-packages/nltk/tag/__init__.py", line 82, in _pos_tag
    tagged_tokens = tagger.tag(tokens)
  File "/Library/Python/2.7/site-packages/nltk/tag/perceptron.py", line 152, in tag
    context = self.START + [self.normalize(w) for w in tokens] + self.END
  File "/Library/Python/2.7/site-packages/nltk/tag/perceptron.py", line 226, in normalize
    elif word[0].isdigit():
IndexError: string index out of range
```

My config file is as follows:

```
# Elasticsearch server
elasticsearch:
  # host where Elasticsearch server is running
  host: "52.40.86.78"
  # port on which Elasticsearch server is listening
  port: 9200

#redis storage
redis:
  host: "127.0.0.1"
  port: 6379

# Corpus to use
corpus:
  # name of the Elasticsearch index where the corpus is stored
  index: "techblogs"
  # name of the Elasticsearch document type where the corpus is stored
  type: "page"
  # list of document fields to generate phrases from
  text_fields: ["text","title"]

timeoutMonitorFrequency: 3600000

# number of documents to process at a time
processingPageSize: 1000

# indicate whether to start annotating from scratch
annotateFromScratch: True
# indicate whether to generate shingles
indexPhrases: True
# indicate whether to generate postags
getPosTags: True

# Processors (add custom processors to list of modules)
processor:
  # name of the Elasticsearch index where annotated text is stored by the processors
  index: "techblogs__annotated"
  # name of the Elasticsearch document type where annotated text is stored by the processors
  type: "page"
  # list of processor modules
  modules:
      # standard bayzee processor to POS tag english text
      # name of the prcessor
    - name: "pos_processor"
      # path to the python module (relative to the location of this config file)
      path: "../lib/pos-processor.py"
      # features that this processor extracts
      features:
        - name: "pos_tags"
          isNumerical: False
        - name: "first_pos_tag"
          isNumerical: False
        - name: "middle_pos_tag"
          isNumerical: False
        - name: "last_pos_tag"
          isNumerical: False
        - name: "avg_word_length"
          isNumerical: True
        - name: "non_alpha_chars"
          isNumerical: True

# Generation
generator:
  # training set file path (relative to the location of this config file)
  trainingPhrasesFilePath: "training-phrases.csv"
  # hold-out set file path (relative to the location of this config file)
  holdOutPhrasesFilePath: "hold-out-phrases.csv"
  # maximum number of words in generated phrase
  maxShingleSize: 3
  # minimum number of words in generated phrase
  minShingleSize: 2
  # list of features to extract
  features:
    - name: "doc_count"
      isNumerical: True
    - name: "max_term_frequency"
      isNumerical: True
    - name: "avg_term_frequency"
      isNumerical: True
    - name: "max_score"
      isNumerical: True
    - name: "avg_score"
      isNumerical: True
  # precision of numerical features
  floatPrecision: 4

# logger config
logger:
  # directory where log files are written (relative to the location of this config file)
  logsDir: "../logs"
```

**Comment by dyoder** [comment]
Were you able to resolve this?

@maheshyellai any ideas?

**Comment by maheshyellai** [comment]
Sorry @desaiuditd and @dyoder somehow missed seeing this one. Will look into it today and let you know.

**Comment by maheshyellai** [comment]
@desaiuditd I didn't find anything that could be causing this error. Could you please let us know which NLTK tokenizer and tagger you are using? For a list of tokenizers and taggers that you may have downloaded: 

```
ls $HOME/nltk_data/tokenizers
ls $HOME/nltk_data/taggers
```

**Comment by mohannnn** [comment]
Hi,
Can someone post a sample record from the ES(initial data with annotation).
My annotator code is running, but generator code stops inbetween.
So, I want to know the correct format to be indexed in ES.

**Comment by XJ-020** [comment]
I met the same error. Have you resolved this?
